services:
    smart_information_systems_sms.transport.configuration_container:
        class: SmartInformationSystems\SmsBundle\Transport\ConfigurationContainer

    sis_sms:
        class: SmartInformationSystems\SmsBundle\Service\Sms
        arguments:
            configuration: "@smart_information_systems_sms.transport.configuration_container"
            container: "@service_container"
            templating: "@templating"
